dist: trusty
language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
install:
  - npm install
script: npm run lint && npm run build && npm test
before_deploy: npm run build
deploy:
  provider: npm
  email: development@platforme.com
  skip_cleanup: true
  api_key:
    secure: tqVUYldiOW3omurdUVWitmcwd+PaOcP5AkuyOINYbqoyP0JaGkTczmytepo6INUSdqTPqUVWdnHghrekjEhbqC9UNVqZ023GiTlSHfqaf/9gO3DYaZoHFSsdzFaLvZnEawdT2K94IyFl+qIyZD9/EO5PIx2/c2F5Ep+5jO8W89+LlQPq9KB7BXNkl5P+xUbLy3Kd2lJvcKwePldDj2TC/g21YzXCeKWkIumwkatWJgorp/nrm+PERE1NObM+hTBxrhCod8pZFrTpmjxhLZfx36Ssb1+minwNm0Wdsru5/f75vVmS1N2Y1CbB+OuIqFwJV7xKbwmix5iUA/1fq03+wCrmcXt098zwOTg7tl3mKbH6KA/Vz8eLicwZ15GsGxjl0Kmk2edC91JOSx6TyIvcuKrXzxVUhVkw673+yW0kMTIISq/hgIVMwPHlsnCVFQv5ItR2EZTEwuJzXWEBzjRzJmE8pNF1vKPXt74K9h8sIMxa230LaCnLmTgWP4REbVeQiinxo0JzbsAkNrJHBqRN7qNwlFf/pmIV9M4etPde/f1AwkrzohdbtsmXxFtCZgSjkMu0/3JXyu7psV9k8xUYQx+lS2ODH9CJZcS0dxzBCJvss+Rcwi4mIYtqi8MakJhcC9ggF0Cvm8qqmLj/nq2rMKR0plrRgheFUGOsQebMgs8=
  on:
    tags: true
    node_js: "10"
